### ISSUE TITLE
Two error

### ISSUE THREAD

**Issue by MinePlugins** [drtshock/SchematicShop#11]
[CODE][14:24:42 WARN]: [SchematicShop] Task #7264 for SchematicShop v1.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()Ljava/util/Collection;
        at com.puzlinc.schematicshop.Events$1.run(Events.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:67) ~[spigot.jar:git-Spigot-unknown]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot.jar:git-Spigot-unknown]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:628) [spigot.jar:git-Spigot-unknown]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283) [spigot.jar:git-Spigot-unknown]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:576) [spigot.jar:git-Spigot-unknown]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:482) [spigot.jar:git-Spigot-unknown]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-unknown]
[/CODE]
And when I place the schem I have an error:
[CODE][14:25:28 WARN]: java.lang.NullPointerException
[14:25:28 WARN]:        at com.puzlinc.schematicshop.Events.onBlockPlace(Events.java:137)
[14:25:28 WARN]:        at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
[14:25:28 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:25:28 WARN]:        at java.lang.reflect.Method.invoke(Method.java:606)
[14:25:28 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
[14:25:28 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:25:28 WARN]:        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:47)
[14:25:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[14:25:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[14:25:28 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:139)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.ItemStack.placeItem(ItemStack.java:133)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:391)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:642)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:180)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:713)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:576)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:482)
[14:25:28 WARN]:        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
[/CODE]

**Comment by drtshock** [comment]
Update craftbukkit.
